version: "3.9"

services:
  database:
    image: mysql:8.0
    container_name: symfony_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql://app:password@database:3306/app?serverVersion=8.0
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - app_network

  mailer:
    image: axllent/mailpit
    container_name: symfony_mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app_network

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - app_network

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli:latest
    container_name: sonar-scanner
    depends_on:
      - sonarqube
    networks:
      - app_network
    volumes:
      - .:/app
    working_dir: /app

volumes:
  db_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

networks:
  app_network:
    driver: bridge